import os
import re
from datetime import datetime

archive_path = r"D:\iCloudDrive\.obsidian\IRP Management\60.Archives\2026\Flomo-Tasks-Archive.md"
checklist_path = r"D:\iCloudDrive\.obsidian\IRP Management\00.Inbox\知识大师_全量Flomo任务清洗_20260418.md"
output_path = r"D:\iCloudDrive\.obsidian\IRP Management\00.Inbox\知识大师_Flomo任务终极清洗去重版_20260418.md"

with open(checklist_path, 'r', encoding='utf-8') as f:
    checklist_content = f.read()

checked_texts = []
for line in checklist_content.split('\n'):
    match = re.match(r'- \[x\] \*\*\d{4}-\d{2}-\d{2}\*\* - (.*)', line)
    if match:
        text_with_br = match.group(1)
        text = text_with_br.replace('<br>', '\n').strip()
        checked_texts.append(text)

with open(archive_path, 'r', encoding='utf-8') as f:
    archive_content = f.read()

entries_raw = archive_content.split("> [!quote] ")
header = entries_raw[0]

unique_tasks = []
seen_texts = set()
deleted_count = 0
duplicate_count = 0
kept_entries_raw = []

def normalize_text(t):
    return re.sub(r'\s+', '', t)

checked_normalized = [normalize_text(t) for t in checked_texts]

for entry in entries_raw[1:]:
    lines = entry.strip().split('\n')
    if not lines:
        continue
    
    date_str = lines[0].strip()
    try:
        entry_date = datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        entry_date = datetime.min
        
    in_frontmatter = False
    frontmatter_dashes = 0
    content_lines = []
    
    for line in lines[1:]:
        line_s = line.strip()
        if line_s == "---" and frontmatter_dashes < 2:
            in_frontmatter = not in_frontmatter
            frontmatter_dashes += 1
            continue
            
        if in_frontmatter:
            continue
            
        if line_s.startswith("#") and "任务" in line_s:
            continue
            
        if line_s == "---" and frontmatter_dashes >= 2:
            continue
            
        content_lines.append(line)

    text = '\n'.join(content_lines).strip()
    if not text:
        continue
        
    norm_text = normalize_text(text)
    
    is_checked = False
    for cn in checked_normalized:
        if cn in norm_text or norm_text in cn:
            is_checked = True
            break
            
    if is_checked:
        deleted_count += 1
        continue
        
    if norm_text in seen_texts:
        duplicate_count += 1
        continue
        
    seen_texts.add(norm_text)
    unique_tasks.append({
        'date_str': date_str,
        'date_obj': entry_date,
        'text': text,
        'raw': "> [!quote] " + entry
    })
    kept_entries_raw.append(entry)

# Write updated archive
new_archive_content = header
if kept_entries_raw:
    new_archive_content += "> [!quote] " + "> [!quote] ".join(kept_entries_raw)
    
with open(archive_path, 'w', encoding='utf-8') as f:
    f.write(new_archive_content)

# Group
unique_tasks.sort(key=lambda x: x['date_obj'], reverse=True)
cutoff_t0 = datetime.strptime("2026-04-01", "%Y-%m-%d")
cutoff_t1 = datetime.strptime("2026-01-01", "%Y-%m-%d")
cutoff_t2 = datetime.strptime("2025-07-01", "%Y-%m-%d")

cat_t0 = []
cat_t1 = []
cat_t2 = []
cat_t3 = []

for t in unique_tasks:
    if t['date_obj'] >= cutoff_t0:
        cat_t0.append(t)
    elif t['date_obj'] >= cutoff_t1:
        cat_t1.append(t)
    elif t['date_obj'] >= cutoff_t2:
        cat_t2.append(t)
    else:
        cat_t3.append(t)

def format_tasks(task_list):
    res = []
    for t in task_list:
        text_lines = t['text'].split('\n')
        first_line = text_lines[0].strip()
        formatted_task = f"- [ ] **{t['date_str']}** - {first_line}"
        for line in text_lines[1:]:
            if line.strip():
                formatted_task += f"<br>{line.strip()}"
        res.append(formatted_task)
    return '\n'.join(res)

markdown = f"""---
tags:
  - 知识大师
  - 任务清洗
  - 批量打勾
  - 去重版
date: 2026-04-18
version: v2
---

# 🧠 知识大师工作流 · Flomo 全量任务去重与深度清洗

> **💡 任务大师清洗心得：**
> 我已为你**彻底清除了重复的任务**（排除了 Flomo 冲突导致的冗余），并且**删除了你已经打勾的已完成/已放弃任务**（这些已同步从源文件档案中永久移除）。
> 
> 现在为你重新梳理剩下的 **{len(unique_tasks)}** 条独立任务。按照你“日期越近越重要，日期越远大概率为无效或过期”的逻辑，我为你设定了四级清算策略。

---

## 🔴 【T0】当下核心执行区 (最近半个月：2026年4月)
> **大师指引：** 这里的任务最新鲜，代表了你当下的需求与卡点。请**认真挑选**，能做的规划到日历，不能做的立刻打勾抛弃。
> *共 {len(cat_t0)} 条*

{format_tasks(cat_t0)}

---

## 🟠 【T1】待转化意图区 (今年内：2026年1月 - 3月)
> **大师指引：** 几个月前的想法，大部分已经不具备执行价值。如果有价值，它们应该是**长期项目（Projects）**或**系统习惯（Areas）**。挑出核心意图，其余全部打勾！
> *共 {len(cat_t1)} 条*

{format_tasks(cat_t1)}

---

## 🟡 【T2】过期焦虑区 (半年前：2025年7月 - 12月)
> **大师指引：** 经过了这么久，这些早就是**过期任务**了。你的生活已经翻篇，这些只是过去的焦虑残影。请享受批量打勾的快感，只保留那些令你茅塞顿开的深刻反思。
> *共 {len(cat_t2)} 条*

{format_tasks(cat_t2)}

---

## 🟢 【T3】无效与历史遗迹区 (2025年7月之前)
> **大师指引：** **绝对无效任务**。请闭上眼睛，全选打勾，彻底埋葬这些执念。
> *共 {len(cat_t3)} 条*

{format_tasks(cat_t3)}

---
*Generated by Claudian Knowledge Master on 2026-04-18*
*统计：本次清除了 {duplicate_count} 条重复任务，删除了 {deleted_count} 条已打勾任务。*
"""

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(markdown)

print(f"Extraction complete! Saved to {output_path}")
print(f"Duplicates removed: {duplicate_count}")
print(f"Checked items deleted: {deleted_count}")
