import os
import re
from datetime import datetime

archive_path = r"D:\iCloudDrive\.obsidian\IRP Management\60.Archives\2026\Flomo-Tasks-Archive.md"
output_path = r"D:\iCloudDrive\.obsidian\IRP Management\00.Inbox\知识大师_全量Flomo任务清洗_20260418.md"

if not os.path.exists(archive_path):
    print(f"Error: {archive_path} not found.")
    exit(1)

with open(archive_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Split by entry
entries_raw = content.split("> [!quote] ")

tasks = []

for entry in entries_raw[1:]: # Skip the first empty/header part
    lines = entry.strip().split('\n')
    if not lines:
        continue
    
    date_str = lines[0].strip()
    
    # Try parsing the date
    try:
        entry_date = datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        entry_date = datetime.min
    
    # Process content: remove frontmatter between --- and ---
    in_frontmatter = False
    frontmatter_dashes = 0
    content_lines = []
    
    for line in lines[1:]:
        line_s = line.strip()
        if line_s == "---" and frontmatter_dashes < 2:
            in_frontmatter = not in_frontmatter
            frontmatter_dashes += 1
            continue
            
        if in_frontmatter:
            continue
            
        # Ignore tags
        if line_s.startswith("#") and "任务" in line_s: # Often it's #任务/紧急 or similar
            continue
        
        # Ignore the trailing ---
        if line_s == "---" and frontmatter_dashes >= 2:
            continue
            
        content_lines.append(line)

    # Clean up empty lines at start/end
    text = '\n'.join(content_lines).strip()
    if not text:
        continue
        
    tasks.append({
        'date_str': date_str,
        'date_obj': entry_date,
        'text': text
    })

# Sort all tasks by date descending
tasks.sort(key=lambda x: x['date_obj'], reverse=True)

# Categorization logic
# Today is 2026-04-18
# T0: >= 2026-02-18 (Last 2 months)
# T1: >= 2025-10-18 (Last 6 months)
# T2: >= 2025-04-18 (Last 1 year)
# T3: < 2025-04-18 (Over 1 year)

cutoff_t0 = datetime.strptime("2026-02-18", "%Y-%m-%d")
cutoff_t1 = datetime.strptime("2025-10-18", "%Y-%m-%d")
cutoff_t2 = datetime.strptime("2025-04-18", "%Y-%m-%d")

cat_t0 = []
cat_t1 = []
cat_t2 = []
cat_t3 = []

for t in tasks:
    if t['date_obj'] >= cutoff_t0:
        cat_t0.append(t)
    elif t['date_obj'] >= cutoff_t1:
        cat_t1.append(t)
    elif t['date_obj'] >= cutoff_t2:
        cat_t2.append(t)
    else:
        cat_t3.append(t)

def format_tasks(task_list):
    res = []
    for t in task_list:
        text_lines = t['text'].split('\n')
        # format as checklist
        first_line = text_lines[0].strip()
        formatted_task = f"- [ ] **{t['date_str']}** - {first_line}"
        for line in text_lines[1:]:
            if line.strip():
                # Append indented on next lines to keep within the checkbox scope
                formatted_task += f"<br>{line.strip()}"
        res.append(formatted_task)
    return '\n'.join(res)

markdown = f"""---
tags:
  - 知识大师
  - 任务清洗
  - 批量打勾
date: 2026-04-18
version: v1
---

# 🧠 知识大师工作流 · Flomo 全量任务终极审判

> **💡 任务大师清洗心法：**
> 任务有“半衰期”。日期越近，属于**执行层**（需要行动）；日期越远，属于**废料层**（直接丢弃）或**意图层**（提炼你的焦虑和渴望）。
> 
> **你的任务：**
> 不要去补做 1 年前的任务，这是内耗。直接把它们**打勾（视为已清理）**。如果看到有价值的想法，提炼出来放到笔记区。
> 
> 共提取出 **{len(tasks)}** 条原始任务。请在下面直接进行打勾清理：

---

## 🔴 【T0】绝对核心区 (最近 2 个月：2026年2月 - 4月)
> **大师指引：** 这些任务仍然鲜活。如果很重要，请规划进下周的日程；如果不打算做，请勇敢打勾承认“我不做了”。
> *共 {len(cat_t0)} 条*

{format_tasks(cat_t0)}

---

## 🟠 【T1】危险保质期 (最近半年：2025年10月 - 2026年2月)
> **大师指引：** 它们已经在你的潜意识里发酵了半年。如果没有引发严重后果，说明它们**根本不紧急**。大部分可以直接打勾超度，少数值得提炼为“习惯”。
> *共 {len(cat_t1)} 条*

{format_tasks(cat_t1)}

---

## 🟡 【T2】严重过期区 (最近一年：2025年4月 - 2025年10月)
> **大师指引：** 这些属于“认知废料”。当年你想买的衣服、想去的地方现在早已无关紧要。请全选、打勾，享受清除它们的快感。如果反复出现同一个主题（如“记账”），提炼为你的底层诉求。
> *共 {len(cat_t2)} 条*

{format_tasks(cat_t2)}

---

## 🟢 【T3】历史遗迹与无效任务 (1 年以前：2025年4月之前及未知)
> **大师指引：** 尘归尘，土归土。请闭着眼直接把这一区打满勾。它们不是任务，是你过去某一天随口叹出的一口气。
> *共 {len(cat_t3)} 条*

{format_tasks(cat_t3)}

---
*Generated by Claudian Knowledge Master on 2026-04-18*
"""

with open(output_path, 'w', encoding='utf-8') as f:
    f.write(markdown)

print(f"Extraction complete! Saved to {output_path}")
